let prompts = [];
let answers = [];

let knowledge = [
  [
    "algoritmo",
    "software",
    "hardware",
    "procesador",
    "memoria",
    "disco",
    "compilador",
    "código",
    "binario",
    "byte",
    "bit",
    "kernel",
    "sistema",
    "red",
    "servidor",
    "cliente",
    "puerto",
    "protocolo",
    "router",
    "switch",
    "firewall",
    "antivirus",
    "malware",
    "spyware",
    "RAM",
    "ROM",
    "SSD",
    "HDD",
    "backup",
    "nube",
    "encriptación",
    "base",
    "datos",
    "SQL",
    "NoSQL",
    "API",
    "interfaz",
    "driver",
    "script",
    "lenguaje",
    "Python",
    "Java",
    "C++",
    "HTML",
    "CSS",
    "JavaScript",
    "PHP",
    "Bash",
    "Linux",
    "Windows",
    "MacOS",
    "BIOS",
    "virtualización",
    "contenedor",
    "Docker",
    "ordenador",
    "Kubernetes",
    "IP",
    "DNS",
    "dominio",
    "hosting",
    "FTP",
    "SSH",
    "VPN",
    "token",
    "hash",
    "debug",
    "bug",
    "parche",
    "actualización",
    "repositorio",
    "Git",
    "GitHub",
    "commit",
    "branch",
    "merge",
    "push",
    "pull",
    "IDE",
    "compilación",
    "ejecución",
    "proceso",
    "hilo",
    "concurrencia",
    "mutex",
    "cola",
    "pila",
    "estructura",
    "recursión",
    "función",
    "variable",
    "clase",
    "objeto",
    "herencia",
    "polimorfismo",
    "encapsulamiento",
    "excepción",
    "stacktrace",
    "rendimiento",
    "latencia",
    "ancho",
    "banda",
    "resolución",
    "pantalla",
    "periférico",
    "teclado",
    "ratón",
    "monitor",
  ],
  [
    "cuchillo",
    "tenedor",
    "cuchara",
    "olla",
    "sartén",
    "cazo",
    "batidora",
    "licuadora",
    "horno",
    "microondas",
    "fogón",
    "espátula",
    "colador",
    "pelador",
    "tabla",
    "báscula",
    "tazón",
    "receta",
    "ingrediente",
    "mezcla",
    "amasar",
    "hervir",
    "freír",
    "asar",
    "cocer",
    "hornear",
    "rehogar",
    "saltear",
    "guisar",
    "emplatar",
    "aceite",
    "sal",
    "azúcar",
    "pimienta",
    "ajo",
    "cebolla",
    "tomate",
    "harina",
    "huevo",
    "leche",
    "mantequilla",
    "nata",
    "crema",
    "queso",
    "pan",
    "arroz",
    "pasta",
    "carne",
    "pescado",
    "pollo",
    "verdura",
    "fruta",
    "legumbre",
    "caldo",
    "sopa",
    "ensalada",
    "postre",
    "bizcocho",
    "tarta",
    "galleta",
    "helado",
    "salsa",
    "vinagre",
    "mostaza",
    "mayonesa",
    "kétchup",
    "curry",
    "canela",
    "orégano",
    "albahaca",
    "perejil",
    "cilantro",
    "romero",
    "tomillo",
    "comino",
    "pimentón",
    "levadura",
    "macerar",
    "marinar",
    "rallar",
    "picar",
    "trocear",
    "cortar",
    "servir",
    "decorar",
    "aderezar",
    "remover",
    "templar",
    "enfriar",
    "refrigerar",
    "congelar",
    "descongelar",
    "temperatura",
    "textura",
    "sabor",
    "aroma",
    "recipiente",
    "plato",
    "cazoleta",
    "vaso",
  ],
  [
    "motor",
    "rueda",
    "neumático",
    "volante",
    "embrague",
    "freno",
    "acelerador",
    "marchas",
    "cambio",
    "transmisión",
    "chasis",
    "carrocería",
    "parachoques",
    "retrovisor",
    "espejo",
    "faros",
    "intermitente",
    "capó",
    "maletero",
    "puerta",
    "ventanilla",
    "parabrisas",
    "limpiaparabrisas",
    "asiento",
    "reposacabezas",
    "cinturón",
    "airbag",
    "tablero",
    "cuentakilómetros",
    "revoluciones",
    "combustible",
    "gasolina",
    "diésel",
    "eléctrico",
    "híbrido",
    "batería",
    "alternador",
    "radiador",
    "escape",
    "silenciador",
    "suspensión",
    "amortiguador",
    "dirección",
    "diferencial",
    "eje",
    "llanta",
    "faro",
    "luz",
    "filtro",
    "aceite",
    "revisión",
    "mecánico",
    "taller",
    "diagnóstico",
    "avería",
    "reparación",
    "garaje",
    "arranque",
    "encendido",
    "velocidad",
    "kilómetro",
    "GPS",
    "sensor",
    "alarma",
    "seguro",
    "matrícula",
    "permiso",
    "carnet",
    "conductor",
    "pasajero",
    "tráfico",
    "señal",
    "carretera",
    "autopista",
    "cruce",
    "rotonda",
    "semáforo",
    "atasco",
    "maniobra",
    "adelantar",
    "frenar",
    "acelerar",
    "girar",
    "estacionar",
    "aparcamiento",
    "marcha",
    "reversa",
    "luces",
    "cambio",
    "claxon",
    "limpiador",
    "palanca",
    "cuadro",
    "retroceso",
    "control",
    "tracción",
    "ABS",
    "ESP",
    "turbo",
    "inyección",
  ],
  [
    "perro",
    "gato",
    "caballo",
    "vaca",
    "oveja",
    "cerdo",
    "conejo",
    "ratón",
    "elefante",
    "león",
    "tigre",
    "jirafa",
    "zebra",
    "mono",
    "gorila",
    "oso",
    "ciervo",
    "reno",
    "canguro",
    "koala",
    "hipopótamo",
    "rinoceronte",
    "búfalo",
    "camello",
    "delfín",
    "ballena",
    "tiburón",
    "pulpo",
    "calamar",
    "estrella de mar",
    "pez",
    "pingüino",
    "águila",
    "halcón",
    "buitre",
    "lechuza",
    "búho",
    "pato",
    "cisne",
    "ganso",
    "paloma",
    "cuervo",
    "loro",
    "canario",
    "avestruz",
    "flamenco",
    "lagarto",
    "serpiente",
    "tortuga",
    "cocodrilo",
    "iguana",
    "camaleón",
    "rana",
    "sapo",
    "abeja",
    "avispa",
    "mosca",
    "mosquito",
    "mariposa",
    "libélula",
    "hormiga",
    "araña",
    "escarabajo",
    "grillo",
    "saltamontes",
    "caracol",
    "lombriz",
    "murciélago",
    "zorro",
    "lobo",
    "puma",
    "pantera",
    "chita",
    "mapache",
    "nutria",
    "castor",
    "erizo",
    "armadillo",
    "topo",
    "hurón",
    "cigüeña",
    "tucán",
    "ornitorrinco",
    "alce",
    "gacela",
    "antílope",
    "mula",
    "burro",
    "gallina",
    "gallo",
    "pollo",
    "pavo",
    "avestruz",
    "pecarí",
    "jabalí",
    "búho",
    "suricata",
    "lémur",
    "perezoso",
    "dromedario",
  ],
  [],
];

const promptBox = document.getElementById("prompt");
const messages = document.querySelector(".messages");
const sendBtn = document.querySelector(".send-btn");

sendBtn.addEventListener("click", () => {
  prompts.push(promptBox.value);

  const newMessage = document.createElement("div");
  const text = document.createElement("p");
  newMessage.classList.add("user-message");
  text.textContent = promptBox.value;
  newMessage.appendChild(text);
  messages.appendChild(newMessage);

  const arrayIndex = messageTreatment(promptBox.value);
  createResponse(arrayIndex);

  promptBox.value = "";
});

function messageTreatment(message) {
  const messageArray = message.split(" ");
  let ticCounter = 0;
  let kitchenCounter = 0;
  let carCounter = 0;
  let animalCounter = 0;
  let arrayIndex = -1;

  messageArray.forEach((word) => {
    if (knowledge[0].includes(word.toLowerCase())) {
      ticCounter++;
    } else if (knowledge[1].includes(word.toLowerCase())) {
      kitchenCounter++;
    } else if (knowledge[2].includes(word.toLowerCase())) {
      carCounter++;
    } else if (knowledge[3].includes(word.toLowerCase())) {
      animalCounter++;
    }

    knowledge[4].push(word.toLowerCase());
  });

  if (
    ticCounter > kitchenCounter &&
    ticCounter > carCounter &&
    ticCounter > animalCounter
  ) {
    arrayIndex = 0;
  } else if (kitchenCounter > carCounter && kitchenCounter > animalCounter) {
    arrayIndex = 1;
  } else if (carCounter > animalCounter) {
    arrayIndex = 2;
  } else if (animalCounter > 0) {
    arrayIndex = 3;
  }

  return arrayIndex;
}

function createResponse(index) {
  const length = Math.floor(Math.random() * 100);
  let iaMessage = "";
  console.log(index);

  for (let i = 0; i < length; i++) {
    let knowledgeThemeIndex = index;

    if (index === -1) {
      knowledgeThemeIndex = Math.floor(Math.random() * knowledge.length);
    }

    knowledgeIndex = Math.floor(
      Math.random() * knowledge[knowledgeThemeIndex].length
    );

    if (i == 0) {
      iaMessage += knowledge[knowledgeThemeIndex][knowledgeIndex];
    } else {
      iaMessage += " " + knowledge[knowledgeThemeIndex][knowledgeIndex];
    }
  }

  const newMessage = document.createElement("div");
  newMessage.classList.add("ia-message");
  newMessage.textContent = iaMessage;
  newMessage.style.opacity = "0";
  messages.appendChild(newMessage);
  setTimeout(() => {
    newMessage.style.opacity = "1";
  }, 10);
}
